CC=CC
STD=c99
CFLAGS=-Wall
MYSTD=$(PWD)/src/std
COMMON=$(MYSTD)/std.c $(MYSTD)/buffer.c $(MYSTD)/algorithms.c
DEST=$(PWD)/bin
SRC=$(PWD)/src

1:
	$(CC) -std=$(STD) $(CFLAGS) $(COMMON) -o $(DEST)/day1 $(SRC)/day1.c


2:
	$(CC) -std=$(STD) $(CFLAGS) $(COMMON) -o $(DEST)/day2 $(SRC)/day2.c
